name: ci

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Install node dependencies
        run: |
          npm i -g pnpm
          pnpm i

      - name: Lint and Check type
        run: |
          pnpm run lint
          pnpm run check

      - name: Build
        run: pnpm run build
